# Changes here will be overwritten by Copier
_commit: v0.3.5
_src_path: https://gitlab.softwareheritage.org/swh/devel/swh-py-template.git
description: Software Heritage authentication utilities
distribution_name: swh-auth
have_cli: true
have_workers: false
package_root: swh/auth
project_name: swh.auth
python_minimal_version: '3.9'
readme_format: rst
